# -*- coding: utf-8 -*-
"""Untitled0.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1AOVjpg947hYx63c-zRlMUQgZIawKQPYF
"""

import pandas as pd
from xgboost import XGBClassifier
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score



df=pd.read_csv("/content/Water_Potability_Data.csv")

df

df.describe()

df.isnull()

df.shape

X=df.iloc[:,:9]
y=df.iloc[:,9]

x

y

seed=7
test_size=0.30
X_train,X_test,y_train,y_test=train_test_split(X,y,test_size=test_size,random_state=seed)

model=XGBClassifier()
model.fit(X_train,y_train)

y_pred=model.predict(X_test)
predictions=[round(value) for value in y_pred]
print(predictions)

accuracy=accuracy_score(y_test,predictions)
print("Accurancy: %.2f%%" %(accuracy * 100.0))

